srand(joinpath(@__DIR__,"SEED"),1)
include(joinpath("..", "docs", "make.jl"))

include("wiener.jl")
include("diffusion.jl")
include("misc.jl")
include("VHK.jl")
include("guip.jl")
include("linpro.jl")
include("timechange.jl")
include("uniformscaling.jl")
include("gamma.jl")